name: "Testing"
description: "create reposository on issue"
inputs:
  github-token:
    description: "Github token"
    required: true
runs:
  using: "composite"
  steps:
    - run: echo CALL ACTION.YML ${{ inputs.github-token }}
      shell: bash
